// Code generated by goctl. DO NOT EDIT.
package types

type DeploymentAddReq struct {
	Name string `json:"name,options=you|me"`
}

type DeploymentAddResp struct {
	Message string `json:"message"`
}

type DeploymentDeleteReq struct {
	Name string `json:"name,options=you|me"`
}

type DeploymentDeleteResp struct {
	Message string `json:"message"`
}

type DeploymentListData struct {
	Name               string `json:"name"`
	Namespace          string `json:"namespace"`
	Labels             string `json:"labels"`
	Strategy           string `json:"strategy"`
	Replicas           int32  `json:"replicas"`
	UpdatedReplicas    int32  `json:"updatedReplicas"`
	ReadyReplicas      int32  `json:"readyReplicas"`
	AvailableReplicas  int32  `json:"availableReplicas"`
	ObservedGeneration int64  `json:"observedGeneration"`
	CreationTimestamp  string `json:"creationTimestamp"`
}

type DeploymentListReq struct {
	Namespace string `json:"namespace,optional"`
}

type DeploymentListResp struct {
	Code int                   `json:"code"`
	Msg  string                `json:"msg"`
	Data []*DeploymentListData `json:"data"`
}

type DeploymentUpdateReq struct {
	Name string `json:"name,options=you|me"`
}

type DeploymentUpdateResp struct {
	Message string `json:"message"`
}

type ImagesData struct {
	Name string `json:"name"`
	Size int64  `json:"size"`
}

type IngressAddReq struct {
	Name string `json:"name,options=you|me"`
}

type IngressAddResp struct {
	Message string `json:"message"`
}

type IngressDeleteReq struct {
	Name string `json:"name,options=you|me"`
}

type IngressDeleteResp struct {
	Message string `json:"message"`
}

type IngressListReq struct {
	Name string `json:"name,options=you|me"`
}

type IngressListResp struct {
	Message string `json:"message"`
}

type NamespaceAddReq struct {
	Name string `json:"name,options=you|me"`
}

type NamespaceAddResp struct {
	Message string `json:"message"`
}

type NamespaceDeleteReq struct {
	Name string `json:"name,options=you|me"`
}

type NamespaceDeleteResp struct {
	Message string `json:"message"`
}

type NamespaceListData struct {
	Name              string `json:"name"`
	Status            string `json:"status"`
	CreationTimestamp string `json:"creationTimestamp"`
}

type NamespaceListReq struct {
	Name string `json:"name,optional"`
}

type NamespaceListResp struct {
	Code int                  `json:"code"`
	Msg  string               `json:"msg"`
	Data []*NamespaceListData `json:"data"`
}

type NodeData struct {
	MachineID               string `json:"machineID"`
	SystemUUID              string `json:"systemUUID"`
	BootID                  string `json:"bootID"`
	KernelVersion           string `json:"kernelVersion"`
	OSImage                 string `json:"oSImage"`
	ContainerRuntimeVersion string `json:"containerRuntimeVersion"`
	KubeletVersion          string `json:"kubeletVersion"`
	KubeProxyVersion        string `json:"kubeProxyVersion"`
	OperatingSystem         string `json:"operatingSystem"`
	Architecture            string `json:"architecture"`
}

type NodesAddReq struct {
	Name string `json:"name,options=you|me"`
}

type NodesAddResp struct {
	Message string `json:"message"`
}

type NodesDeleteReq struct {
	Name string `json:"name,options=you|me"`
}

type NodesDeleteResp struct {
	Message string `json:"message"`
}

type NodesListData struct {
	Name              string        `json:"name"`
	Status            string        `json:"status"`
	Memory            string        `json:"memory"`
	NodeInfo          NodeData      `json:"nodeInfo"`
	Images            []*ImagesData `json:"Images"`
	CreationTimestamp string        `json:"creationTimestamp"`
}

type NodesListReq struct {
	Name string `json:"name,optional"`
}

type NodesListResp struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data []*NodesListData `json:"data"`
}

type PodsAddReq struct {
	Name string `json:"name,options=you|me"`
}

type PodsAddResp struct {
	Message string `json:"message"`
}

type PodsDeleteReq struct {
	Name string `json:"name,options=you|me"`
}

type PodsDeleteResp struct {
	Message string `json:"message"`
}

type PodsListData struct {
	Name              string `json:"name"`
	Status            string `json:"status"`
	Labels            string `json:"labels"`
	Namespace         string `json:"namespace"`
	HostIP            string `json:"hostIP"`
	PodIP             string `json:"podIP"`
	StartTime         string `json:"startTime"`
	RestartCount      int32  `json:"restartCount"`
	Image             string `json:"image"`
	CreationTimestamp string `json:"creationTimestamp"`
}

type PodsListReq struct {
	Name string `json:"name,optional"`
}

type PodsListResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data []*PodsListData `json:"data"`
}

type ServiceAddReq struct {
	Name string `json:"name,options=you|me"`
}

type ServiceAddResp struct {
	Message string `json:"message"`
}

type ServiceDeleteReq struct {
	Name string `json:"name,options=you|me"`
}

type ServiceDeleteResp struct {
	Message string `json:"message"`
}

type ServiceListData struct {
	Name              string `json:"name"`
	Namespace         string `json:"namespace"`
	Labels            string `json:"labels"`
	Selector          string `json:"selector"`
	Type              string `json:"type"`
	ClusterIP         string `json:"clusterIP"`
	Protocol          string `json:"protocol"`
	Ports             int32  `json:"ports"`
	TargetPort        int32  `json:"targetPort"`
	NodePort          int32  `json:"nodePort"`
	CreationTimestamp string `json:"creationTimestamp"`
}

type ServiceListReq struct {
	Namespace string `json:"namespace"`
}

type ServiceListResp struct {
	Code int                `json:"code"`
	Msg  string             `json:"msg"`
	Data []*ServiceListData `json:"data"`
}
