// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"k8s_test/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/namespace/list",
				Handler: NamespaceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/namespace/add",
				Handler: NamespaceAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/namespace/delete",
				Handler: NamespaceDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/deployment/list",
				Handler: DeploymentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/deployment/add",
				Handler: DeploymentAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/deployment/update",
				Handler: DeploymentUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/deployment/delete",
				Handler: DeploymentDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/service/list",
				Handler: ServiceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/service/add",
				Handler: ServiceAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/service/delete",
				Handler: ServiceDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/ingress/list",
				Handler: IngressListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/ingress/add",
				Handler: IngressAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/ingress/delete",
				Handler: IngressDeleteHandler(serverCtx),
			},
		},
	)
}
